# Generated by Django 3.1.2 on 2020-11-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alternate_mobile_no',
            field=models.CharField(max_length=30),
        ),
    ]
