# Generated by Django 3.1.2 on 2020-11-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoreapp', '0006_auto_20201128_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
