# Generated by Django 3.1.2 on 2020-11-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoreapp', '0007_orderitem_out_of_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='out_of_stock',
        ),
        migrations.AddField(
            model_name='item',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
